sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: WwFQrXGGayUKj1qzxygTqA9Lwc+8JHXfe1vQAkL2pBcYL8/E7XliUhEtlroOVsV2aziNNHh0VlECj8vHzzW1cySU7AWpmmsOCjNI8E3iyXdEwLzBN56QEWEj/eojpBS1Ap7qXxMX2+Nkdu0hclHwqwgQyelIpc+V5k0qfR9wa/x6LRfeJAxdOVrSlXF6juNVgCER92dIdpVFkKdsnNQ6VtnVwgWR9I15eum0Dh6ClDAlK5v9FztahRc3zdVhPrCSCDqHiLyO7FdfnCch/wVZM/br4PU5m4eo8IKJl4mbuKSLJvSR6SHg8PxVvUp2CzbEbzFezYhDVwx6NMnsqjoWlnQ69fkfIvQqvqAeNH0Ni+1R8hRpUJIQD1sNs2g1Up/g2LL3iGlRiMc/XTnoFTFJhBf/9I4nBuEnjyFta2tnRlJnWwTAa0+NVUPgwEw59TaOBgA02nPDyJB+VXKNH5jlT6gHhkaiEP+8R5Ry9g5w7XvfJHbKUs47menzhHrqJBx7F8y6vIjLoFjW++ypTIciCvugrEAn5YsoAGOTpYAUEwo//rGoD97IX4JPwRv3BSWXMT34FjFy40V3dX58vkaqzhVa/bDV5u79E6nM6Y2jzIvZq3LYNO5gH/eo/xhwq5tLW28yTuUEwh+UY/vG+f9MqcJ3lLkpAp1hdaYpXYMSSQU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/King-Midas--a-Romance_4923
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy